from .bitcoinlib.script import *

class AllowedOp:
    OP_AND = OP_AND
    OP_OR = OP_OR
    OP_NOT = OP_NOT
    OP_CHECKSIGVERIFY = OP_CHECKSIGVERIFY
    OP_SHA256 = OP_SHA256
    OP_EQUAL = OP_EQUAL
    OP_DROP = OP_DROP
    OP_PICK = OP_PICK
    OP_DEPTH = OP_DEPTH
    OP_SUB = OP_SUB
    OP_2DROP = OP_2DROP
    OP_1SUB = OP_1SUB
    OP_IFDUP = OP_IFDUP
    OP_NOTIF = OP_NOTIF
    OP_ENDIF = OP_ENDIF
    OP_0 = OP_0
    OP_CHECKTEMPLATEVERIFY = OP_CHECKTEMPLATEVERIFY
    OP_CHECKLOCKTIMEVERIFY = OP_CHECKLOCKTIMEVERIFY
    OP_CHECKSEQUENCEVERIFY = OP_CHECKSEQUENCEVERIFY
    OP_DUP = OP_DUP
    OP_WITHIN = OP_WITHIN
    OP_VERIFY = OP_VERIFY
    OP_IF = OP_IF
    OP_ELSE = OP_ELSE

