[workspace]
resolver = "2"
members = ["blocks", "emulation", "modules/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.98.1"
license = "MPL-2.0"
publish = false

[workspace.dependencies]
build-a-vault-blocks = { path = "blocks" }
build-a-vault-emulation = { path = "emulation" }
bitcoin = { version = "=0.32.102", features = ["serde"] }
schemars = { version = "=1.2.2", features = ["bitcoin032", "miniscript13"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sapio = { path = "../../sapio" }
sapio-base = { path = "../../sapio-base" }
sapio-wasm-plugin = { path = "../../plugins", features = ["client"] }

[patch.crates-io]
bitcoin = { git = "https://github.com/sapio-lang/rust-bitcoin", rev = "6ef940bb2d98ba5dece053fdabd1d9ad65ff5864" }
bitcoin_hashes = { git = "https://github.com/sapio-lang/rust-bitcoin", rev = "6ef940bb2d98ba5dece053fdabd1d9ad65ff5864" }
miniscript = { git = "https://github.com/sapio-lang/rust-miniscript", rev = "8d2aa4a60979a55f6ecd6222d48f94a482f4a2f6" }
schemars = { git = "https://github.com/sapio-lang/sapio-jsonschema", rev = "1ab5dcacb79fa9f068b1f3d8759bcd489564c989" }
schemars_derive = { git = "https://github.com/sapio-lang/sapio-jsonschema", rev = "1ab5dcacb79fa9f068b1f3d8759bcd489564c989" }

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
strip = "debuginfo"
