[package]
rust-version.workspace = true
name = "sapio-cli"
version = "0.2.4"
license = "MPL-2.0"
authors = ["Jeremy Rubin <j@rubin.io>"]
edition = "2021"
repository = "https://github.com/sapio-lang/sapio"
homepage = "https://sapio-lang.org"
description = "A Command Line Interface for interacting with Sapio Contracts"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = { version = "=1.2.2", features = ["bitcoin032", "miniscript13"] }
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
clap = "=3.0.0-beta.2"
base64 = "0.13.0"
lazy_static = "1.4.0"
bitcoincore-rpc = "0.19.0"
tokio = { version = "1", features = ["full"] }
directories = "3.0.1"
rand = "0.8.5"

[dependencies.sapio-psbt]
path = "../sapio-psbt"
version = "0.2.4"

[dependencies.bitcoin]
version = "=0.32.102"
features = ['serde', 'rand', 'base64']


[dependencies.sapio]
path = "../sapio"
version = "0.2.0"

[dependencies.sapio-base]
path = "../sapio-base"
version = "0.2.0"

[dependencies.ctv_emulators]
path = "../ctv_emulators"
version = "0.2.0"

[dependencies.sapio-contrib]
path = "../sapio-contrib"
version = "0.2.0"

[dependencies.sapio-wasm-plugin]
path = "../plugins"
version = "0.2.0"

features = ["host"]
