[package]
rust-version.workspace = true
name = "sapio-wasm-plugin"
version = "0.2.4"
license = "MPL-2.0"
authors = ["Jeremy Rubin <j@rubin.io>"]
edition = "2021"
repository = "https://github.com/sapio-lang/sapio"
homepage = "https://sapio-lang.org"
description = "Libarary for building client/host sapio plugin bindings"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["client"]
host = ["wasmer", "wasmer-cache", "wasmer-middlewares", "wasmer-types", "jsonschema", "referencing", "tokio"]
client = []

[dependencies]
schemars = "0.8.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
base64 = "0.13.0"
hex = "0.4.3"

[dependencies.wasmer]
version = "6.1.0"
optional = true

[dependencies.wasmer-cache]
version = "6.1.0"
optional = true

[dependencies.wasmer-middlewares]
version = "=6.1.0"
optional = true

[dependencies.wasmer-types]
version = "=6.1.0"
optional = true

[dependencies.jsonschema]
version = "=0.55.0"
default-features = false
optional = true

[dependencies.referencing]
version = "=0.55.1"
optional = true

[dependencies.tokio]
version = "1"
optional = true
features = ["full"]

[dependencies.bitcoin]
package = "sapio-bitcoin"
version = "0.28.0"
features = ['use-serde']
[dependencies.sapio]
path = "../sapio"
version = "0.2.0"

[dependencies.sapio-base]
path = "../sapio-base"
version = "0.2.0"

[lib]
path = "src/lib.rs"

[[example]]
name = "check_examples"
required-features = ["host"]


[package.metadata.wasm-pack.profile.release]
wasm-opt = false
